[project]
name = "treethink"
version = "0.1.0"
description = "Formal Mathematical Reasoning of LLMs with Tree Search Methods"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.8.5",
    "kimina-client",
    "toml>=0.10.2",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
main = [
    "vllm>=0.8.5.post1",
]
build = [
    "setuptools>=75.8.0",
]
direct = [
    "vllm>=0.8.5.post1",
]

[tool.uv]
default-groups = ["main", "build", "direct"]

[tool.uv.sources]
kimina-client = { git = "https://github.com/project-numina/kimina-lean-server.git" }
