"""Node implementation to be used with different inference time methods."""

import json
from typing import Iterable, List, Optional

from vllm import CompletionOutput


class Node:
    """Tree node for representing states in proof-search trees.

    Each node represents a proof state and tracks exploration metrics for
    search algorithms.  Nodes form a tree via parent-child relationships,
    with ``win_value`` and ``visits`` used to compute average node quality.

    Key properties:
    - ``is_termination_node`` — ``True`` when ``text == termination_str``
    - ``is_expandable`` — ``True`` if not expanded and not a termination node
    - ``answer`` — the complete proof from the root to this node (the
      concatenation of every ancestor's ``text``), with ``rollout_output``
      appended when present.  This is what REPL/formal evaluators consume.

    Key methods:
    - ``add_children()`` — attach multiple child nodes
    - ``remove_duplicate_children()`` — deduplicate by text
    - ``print_node()`` — generate graphviz DOT output
    - ``traverse_to_root()`` — walk from this node back to the root
    - ``parse_proof()`` — extract proof text from code fences
    """

    def __init__(
        self,
        text: Optional[str] = None,
        max_children: Optional[int] = None,
        level: int = 0,
        parent: Optional["Node"] = None,
        vllm_output: Optional[CompletionOutput] = None,
        termination_str: Optional[str] = None,
        exploration_weight: Optional[float] = None,
        *args,
        **kwargs,
    ):
        self.text = text
        self.max_children = max_children
        self.level: int = level if parent is None else parent.level + 1
        self.parent = parent
        self.vllm_output = vllm_output
        self.termination_str = termination_str
        self.exploration_weight = exploration_weight

        self.children: List["Node"] = []
        self.win_value = 0
        self.visits = 0
        self.id = id(self)
        self.is_widen_node = False

        # Complete proof continuation generated by a rollout (e.g. by
        # ``TraditionalMCTS``).  When set, it is appended to ``answer`` so
        # that formal evaluators verify the full candidate proof.
        self.rollout_output: Optional[str] = None

    @property
    def answer(self) -> str:
        """The complete proof from the root down to (and including) this node.

        Concatenates the ``text`` of every node on the root-to-self path,
        then appends ``rollout_output`` when a rollout continuation is
        present.  This is the proof string consumed by REPL/formal
        evaluators (e.g. :class:`LeanREPLEvaluator`).
        """
        parts: List[str] = []
        current: Optional["Node"] = self
        while current is not None:
            parts.append(current.text or "")
            current = current.parent
        parts.reverse()
        proof = "".join(parts)
        if self.rollout_output:
            proof += self.rollout_output
        return proof

    def remove_duplicate_children(self) -> None:
        """
        Remove duplicate children based on their text property.
        Keeps the first occurrence of each unique text value.
        """
        if not self.children:
            return

        seen_texts = set()
        unique_children = []

        for child in self.children:
            if child.text not in seen_texts:
                seen_texts.add(child.text)
                unique_children.append(child)

        self.children = unique_children

    @property
    def is_termination_node(self) -> bool:
        return (
            self.termination_str == self.text if self.termination_str else False
        )

    @property
    def is_root_node(self) -> bool:
        return self.parent is None

    @property
    def is_expandable(self) -> bool:
        """Whether the node is ready for expansion.

        Checks both children_count < max_children and termination_str if it
        exists.
        """
        return len(self.children) == 0 and not self.is_termination_node

    def is_fully_expanded(self) -> bool:
        """
        Checks if the node is fully expanded, meaning it has the maximum number of children.

        Returns:
            bool: True if the node is fully expanded, False otherwise.
        """
        return len(self.children) >= self.max_children

    def add_child(self, child):
        self.children.append(child)
        child.parent = self

    def add_children(self, children: Iterable):
        for child in children:
            self.add_child(child)

    def _get_min_max_win_value(self):
        """
        Find min and max win_value in subtree rooted at this node.

        Returns:
            tuple: (min_value, max_value)
        """
        min_val = self.win_value
        max_val = self.win_value

        for child in self.children:
            child_min, child_max = child._get_min_max_win_value()
            min_val = min(min_val, child_min)
            max_val = max(max_val, child_max)

        return min_val, max_val

    def print_node(self, f, i, st, solution=None):
        """Write the tree rooted at this node in graphviz DOT format.

        Args:
            f: File object to write to.
            i: Indentation level.
            st: String identifier for this node (e.g. ``"a"``, ``"a_0"``).
            solution: If provided, nodes on the solution path are coloured
                red.  Each node's text must match the corresponding prefix
                of the solution string.
        """

        def _escape(x):
            return json.dumps(x).strip('"')

        stack = [(self, i, st, solution)]

        while stack:
            node, node_i, node_st, node_solution = stack.pop()
            text_content = node.text

            # Escape HTML-special characters
            text_content = (
                text_content.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace('"', "&quot;")
            )

            # HTML-like table label with win value, visits, and level
            label = (
                '<<TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0">'
                f'<TR><TD ROWSPAN="3">{_escape(text_content)}</TD>'
                f'<TD ALIGN="RIGHT"><FONT POINT-SIZE="10">W:{round(node.win_value, 3)}</FONT></TD></TR>'
                f'<TR><TD ALIGN="RIGHT"><FONT POINT-SIZE="10">V:{node.visits}</FONT></TD></TR>'
                f'<TR><TD ALIGN="RIGHT"><FONT POINT-SIZE="10">L:{node.level}</FONT></TD></TR>'
                "</TABLE>>"
            )

            # NOTE(burak): I have tried different colorings but single red
            # color seems to be sufficient.  If we change it to something
            # else, we need to update default identifier arguments
            # functions in graph.py
            on_path = (
                node_solution is not None
                and node_solution[: len(node.text)] == node.text
            )
            attr = "penwidth=2"
            if on_path:
                attr += ",color=red"

            f.write(
                (" " * node_i) + f"{node_st} [label={label},shape=box,{attr}]\n"
            )

            # Push children in reverse order so the first child is
            # processed first (LIFO stack).  Write edges immediately —
            # DOT does not require a particular edge/node order.
            children = list(node.children)
            for idx in range(len(children) - 1, -1, -1):
                child = children[idx]
                child_st = node_st + "_" + str(idx)
                child_solution = (
                    None if not on_path else node_solution[len(node.text) :]
                )
                f.write(" " * node_i + node_st + " -- " + child_st + "\n")
                stack.append((child, node_i + 2, child_st, child_solution))

    def most_visited_child(self) -> "Node":
        """
        Selects the child node with the highest number of visits.

        Returns:
            Node: The most visited child node.
        """
        return max(self.children, key=lambda child: child.visits)

    def __str__(self) -> str:
        _escaped = self.text.replace("\n", "\\n")
        return f"Node(visits={self.visits},win_value={self.win_value},text={_escaped})"

    def __repr__(self) -> str:
        return self.__str__()

    def __eq__(self, other):
        if not isinstance(other, Node):
            raise NotImplementedError(
                f"Can not compare type {type(other)} and Node."
            )
        return (
            self.text == other.text
            and self.level == other.level
            and self.max_children == other.max_children
            and self.termination_str == other.termination_str
        )


def get_total_child_num(node: Node):
    """Get the number of total child nodes recursively."""
    if not node.children:
        return 1

    total = 1  # Count this node
    for child in node.children:
        total += get_total_child_num(child)

    return total
