import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        "commands",
        "helpers",
        "main",
    },
    submod_attrs={
        "commands": [
            "analyze",
            "extract",
            "graph",
            "help_cmd",
            "info",
            "run",
            "show_help",
            "visualize",
        ],
        "helpers": [
            "ASYNC_EVALUATOR_MAP",
            "ASYNC_METHOD_MAP",
            "ASYNC_POLICY_MAP",
            "build_graph_stats_payload",
            "config",
            "convert_to_async",
            "dry_run",
            "get_time",
            "graph_stats",
            "infer_graph_dir",
            "iteration",
            "logging_setup",
            "parse_inference_arguments",
            "run_async_iterations",
            "run_inference_loop",
            "setup_logging",
            "setup_model",
            "simple_messages_to_string",
        ],
        "main": [
            "app",
            "graph_app",
            "main",
        ],
    },
)

__all__ = [
    "ASYNC_EVALUATOR_MAP",
    "ASYNC_METHOD_MAP",
    "ASYNC_POLICY_MAP",
    "analyze",
    "app",
    "build_graph_stats_payload",
    "commands",
    "config",
    "convert_to_async",
    "dry_run",
    "extract",
    "get_time",
    "graph",
    "graph_app",
    "graph_stats",
    "help_cmd",
    "helpers",
    "infer_graph_dir",
    "info",
    "iteration",
    "logging_setup",
    "main",
    "parse_inference_arguments",
    "run",
    "run_async_iterations",
    "run_inference_loop",
    "setup_logging",
    "setup_model",
    "show_help",
    "simple_messages_to_string",
    "visualize",
]
