import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        "args",
        "enums",
        "funcs",
        "load",
        "parser",
        "str_manip",
    },
    submod_attrs={
        "args": [
            "BaseArgs",
            "ClientArgs",
            "EvaluatorArgs",
            "ModelArgs",
            "PolicyArgs",
            "SamplingArgs",
            "ServerArgs",
            "TerminationOnEncounterConfig",
            "TerminationOnPathsConfig",
            "TreeThinkArgs",
        ],
        "enums": [
            "BestAnswerReason",
            "EnumType",
            "FinalDecisionMode",
            "ProofLanguage",
            "PoolingTask",
            "ScoreReduction",
            "TieBreaker",
            "coerce_enum",
        ],
        "funcs": [
            "calculate_logprobs",
        ],
        "load": [
            "load_dataset",
            "load_hf_dataset",
            "load_json_dataset",
            "load_jsonl_dataset",
        ],
        "parser": [
            "T",
            "drop_none",
            "parse_normal_inference_args",
            "parse_treethink_args",
            "serialize_args",
        ],
        "str_manip": [
            "check_tags",
            "extract_result",
        ],
    },
)

__all__ = [
    "BaseArgs",
    "BestAnswerReason",
    "ClientArgs",
    "EnumType",
    "EvaluatorArgs",
    "FinalDecisionMode",
    "ProofLanguage",
    "ModelArgs",
    "PolicyArgs",
    "PoolingTask",
    "SamplingArgs",
    "ScoreReduction",
    "ServerArgs",
    "T",
    "TerminationOnEncounterConfig",
    "TerminationOnPathsConfig",
    "TieBreaker",
    "TreeThinkArgs",
    "args",
    "calculate_logprobs",
    "check_tags",
    "coerce_enum",
    "drop_none",
    "enums",
    "extract_result",
    "funcs",
    "load",
    "load_dataset",
    "load_hf_dataset",
    "load_json_dataset",
    "load_jsonl_dataset",
    "parse_normal_inference_args",
    "parse_treethink_args",
    "parser",
    "serialize_args",
    "str_manip",
]
