import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        "adapter",
        "client",
        "proof_utils",
    },
    submod_attrs={
        "adapter": [
            "AsyncLeanClientAdapter",
            "LeanClientAdapter",
        ],
        "client": [
            "Lean4Client",
            "WRAPPER_TACTICS",
            "adjust_intervals",
            "batch_verify_proof",
            "client",
            "ends_with_by",
            "extract_data",
            "extract_nodes_and_edges",
            "get_intervals",
            "infotree",
            "is_balanced",
            "is_by",
            "is_calc",
            "is_wrapper",
            "merge_intervals",
            "process_batch",
            "process_batches",
            "remove_lean_comments",
            "retrieve_tactics",
            "separate_trailing_comment",
            "separate_trailing_whitespace",
            "transfer_trailing_whitespaces_and_comments",
        ],
        "proof_utils": [
            "analyze",
            "analyze_sample",
            "get_error_msg",
            "get_messages_for_lines",
            "has_error_response",
            "parse_client_response",
            "parse_error_message",
            "parse_lean_response",
            "parse_messages",
            "split_proof_header",
        ],
    },
)

__all__ = [
    "AsyncLeanClientAdapter",
    "Lean4Client",
    "LeanClientAdapter",
    "WRAPPER_TACTICS",
    "adapter",
    "adjust_intervals",
    "analyze",
    "analyze_sample",
    "batch_verify_proof",
    "client",
    "ends_with_by",
    "extract_data",
    "extract_nodes_and_edges",
    "get_error_msg",
    "get_intervals",
    "get_messages_for_lines",
    "has_error_response",
    "infotree",
    "is_balanced",
    "is_by",
    "is_calc",
    "is_wrapper",
    "merge_intervals",
    "parse_client_response",
    "parse_error_message",
    "parse_lean_response",
    "parse_messages",
    "process_batch",
    "process_batches",
    "proof_utils",
    "remove_lean_comments",
    "retrieve_tactics",
    "separate_trailing_comment",
    "separate_trailing_whitespace",
    "split_proof_header",
    "transfer_trailing_whitespaces_and_comments",
]
